### ISSUE TITLE
Crear usuario PostgreSQL y usarlo en Rails

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2143-2020-1/proyecto#53]
Hola!!
Solo quería saber cual es el nombre de usuario por default para postgresql, ya que al instalarlo sólo me pidió crear una contraseña, pero en ningún momento me solicitó crear un nombre de usuario.

Por lo que para vincular a Rails con postgresql necesito este nombre de usuario. En internet indica que por default es postgres pero no sé si es así. 

Además me gustaría saber si se puede cambiar este nombre de usuario por default y cómo.

**Comment by rialonsom** [comment]
Hola @benito-tondreaux! 

El nombre de usuario por defecto de postgresql es "postgres" y la contraseña la eliges tu al momento de la instalación. En vez de cambiar el nombre de usuario, algo más fácil que puedes hacer es crear uno nuevo y vincular este nuevo usuario a tu proyecto de Rails. Puedes crear un nuevo usuario desde la consola de postgres ejecutando el siguiente comando:

`CREATE USER nombre_usuario WITH PASSWORD 'contraseña' SUPERUSER;`

Reemplazando "nombre_usuario" y "contraseña" por lo que tu elijas.

**Comment by benito-tondreaux** [comment]
Graciaaas!!

Otra pregunta, como vinculo este nuevo usuario al proyecto de Rails?? Dejando ese nombre como el usuario cuando configuro Rails con Postgres??

**Comment by rialonsom** [comment]
Efectivamente, en el archivo `config/database.yml` de tu proyecto es necesario especificar para las bases de datos de `development` y `test` el `username`  y `password` que definiste antes. Algo así:

```
# ... aquí hay código

development:
  # ... más código

  username: # Aquí va tu usuario
  password: # Aquí va tu contraseña

  # ... más código

test:
  # ... más código

  username: # Aquí va tu usuario
  password: # Aquí va tu contraseña

  # ... más código

```
