### ISSUE TITLE
Problemas con rails

### ISSUE THREAD

**Issue by fernandovegauc** [IIC2143-2020-1/proyecto#88]
Hola, hoy empecé a ocupar ubuntu ya que tuve muchos problemas con windows. Finalmente  pude instalar postgresql, ahora tengo un problema al momento de crear una base de datos. He intentado solucionarlo con las issues pero no he podido :(
![Screenshot from 2020-04-11 19-47-35](https://user-images.githubusercontent.com/53880431/79057320-3eabae80-7c2e-11ea-8455-10bd0167fda4.png)

**Comment by daleal** [comment]
Hola! Parece ser un tema de permisos del usuario que estás usando en Postgres. Podrías mandarme el contenido de tu archivo `config/database.yml` por favor? (como _formatted text_, no como imagen :heart:)

**Comment by fernandovegauc** [comment]
Holaaa, eso es lo que tengo en el archivo (eliminé todos los comentarios).Ya probé con username:postgres :( 

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  username: fernando
  password:

 
test:
  <<: *default
  database: app_test
  username: fernando
  password:

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
```
Gracias
